### ISSUE TITLE
Feature Request for Enhancing Workflow for Traffic Signal Mapping

### ISSUE THREAD

**Issue by poornibadrinath** [mapbox/traffic-signals#1]
Follow up of this issue [#100](https://github.com/mapbox/osm-navigation-map/issues/100#issuecomment-265397450) from the [OSM navigation map repo](https://github.com/mapbox/osm-navigation-map)

Since these two maps are separate, creating a new issue here for the traffic signal map updates. 

----------------------

#### Feature requests: 

- Pop up 
- Highlighting intersections for major roads and that of where the minor roads meet major roads. 

As mentioned in this [issue](https://github.com/mapbox/osm-navigation-map/issues/100)

/cc: @ajithranka

**Comment by ajithranka** [comment]
Done.
